# Generated by Django 3.2.9 on 2024-11-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
